#!/bin/bash

echo "=== Native Linux Tracing Example ==="
echo ""
echo "This script provides instructions for running kernel-level tracing."
echo "This requires a native Linux installation and 'bpftrace' to be installed."
echo ""
echo "1. Open two terminal windows."
echo ""
echo "2. In Terminal 1, start the tracing script as root:"
echo "   sudo bpftrace trace/bpf/full_path.bt | tee results/trace_raw.txt"
echo ""
echo "3. In Terminal 2, run the pinned benchmark:"
echo "   taskset -c 0 ./build/baseline 10000"
echo ""
echo "4. After the benchmark finishes, stop Terminal 1 with Ctrl-C."
echo ""
echo "5. Parse the results:"
echo "   python3 tools/parse_trace.py results/trace_raw.txt"
echo ""
echo "Note: These scripts will not work inside standard WSL without a custom kernel with BTF enabled."
